sudo: required
services:
  - docker

before_install:
  - docker build -t nikhilgupta1112/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nikhilgupta1112/react-test npm test -- --coverage

after_success:
  - docker build -t nikhilgupta1112/multi-client ./client
  - docker build -t nikhilgupta1112/multi-nginx ./nginx
  - docker build -t nikhilgupta1112/multi-server ./server
  - docker build -t nikhilgupta1112/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub.
  - docker push nikhilgupta1112/multi-client
  - docker push nikhilgupta1112/multi-nginx
  - docker push nikhilgupta1112/multi-server
  - docker push nikhilgupta1112/multi-worker